target 'TeslaSwift' do
	use_frameworks!
	platform :ios, '12.0'

    pod 'Starscream', '~> 4.0.4'
    pod 'PromiseKit/CorePromise' , '~> 6'

    pod 'RxSwift', '~> 6.5.0'
    pod 'RxCocoa', '~> 6.5.0'

	target 'TeslaSwiftTests' do
		
		pod 'OHHTTPStubs'
		pod 'OHHTTPStubs/Swift'
		
	end
end

