target 'TeslaSwift' do
	use_frameworks!
	platform :ios, '10.0'

    pod 'Starscream', '~> 3'
	pod 'PromiseKit/CorePromise' , '~> 6'
    
    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'

	target 'TeslaSwiftTests' do
		
		pod 'OHHTTPStubs'
		pod 'OHHTTPStubs/Swift'
		
	end
end

